### ISSUE TITLE
#6 Pipeline: Build end-to-end content generation and scheduling system

### ISSUE THREAD

**Issue by prof-schacht** [prof-schacht/coai-linkedin-content-pipeline#6]
## 📋 Overview
Create the content generation pipeline that brings everything together - from data collection through agent processing to final post creation. This orchestrates the entire workflow and produces ready-to-publish LinkedIn content.

## 🎯 Goals
- Integrate all components into a cohesive pipeline
- Generate 1-2 high-quality posts daily
- Extract and process paper figures for visuals
- Ensure content authenticity and relevance
- Create a review/approval interface

### 1. Pipeline Orchestrator
- [ ] Create `src/generators/post_creator.py`
- [ ] Implement main pipeline flow:
  ```python
  class ContentPipeline:
      def daily_run(self):
          # 1. Fetch latest papers and X posts
          # 2. Score and rank content
          # 3. Run CrewAI agents
          # 4. Generate posts
          # 5. Extract visuals
          # 6. Queue for review
  ```
- [ ] Add error handling and retries

### 2. Content Scoring System
- [ ] Rank content opportunities by:
  - Paper novelty/importance
  - X.com discussion heat
  - Relevance to COAI mission
  - Visual potential
  - Timeliness
- [ ] Select top 2-3 items for posts

### 3. Visual Content Extraction
- [ ] Implement figure extraction from papers:
  ```python
  def extract_paper_figures(pdf_path):
      # Extract images/charts
      # Filter for quality
      # Add captions
      # Resize for LinkedIn
  ```
- [ ] Create fallback visualizations
- [ ] Ensure proper attribution

### 4. Post Assembly
- [ ] Combine all elements:
  - Agent-generated text
  - Visual content
  - Hashtags (#AISafety #MechanisticInterpretability)
  - Mentions (@connections)
  - Links (paper, COAI website)
- [ ] Format for LinkedIn's requirements

### 5. Review Interface
- [ ] Create `scripts/review_posts.py`
- [ ] Build simple CLI/web interface:
  ```
  === Post Review ===
  Content: [Generated post text]
  Visual: [Figure preview]
  Mentions: [@person1, @person2]
  Score: 8.5/10
  
  Actions: [Approve] [Edit] [Reject] [Regenerate]
  ```
- [ ] Store approved posts

### 6. Scheduling System
- [ ] Create posting schedule:
  - Optimal times (Tuesday-Thursday, 8-10 AM)
  - Avoid over-posting
  - Space out topics
- [ ] Queue approved posts
- [ ] Track posting history

### 7. Database Integration
- [ ] Create generated_posts table:
  ```sql
  CREATE TABLE generated_posts (
      id SERIAL PRIMARY KEY,
      paper_id INTEGER REFERENCES papers(id),
      x_post_ids INTEGER[],
      content TEXT,
      visual_path TEXT,
      mentions TEXT[],
      hashtags TEXT[],
      quality_score FLOAT,
      status VARCHAR(20), -- draft, approved, posted
      scheduled_for TIMESTAMP,
      posted_at TIMESTAMP,
      engagement_data JSONB,
      created_at TIMESTAMP DEFAULT NOW()
  );
  ```

## 📝 Acceptance Criteria
- Pipeline runs end-to-end without errors
- Generates 1-2 quality posts per run
- Posts include relevant visuals
- Content passes authenticity check
- Review interface is user-friendly
- Posts are properly scheduled

## 🔗 Resources
- [LinkedIn Post Best Practices](https://www.linkedin.com/help/linkedin/answer/700)
- [PyMuPDF for PDF processing](https://pymupdf.readthedocs.io/)
- [Pillow for image processing](https://pillow.readthedocs.io/)

## 💡 Tips
- Test with real paper examples
- A/B test different post formats
- Monitor which visuals perform best
- Build a library of successful patterns
- Keep posts under 3000 characters

## 📊 Example Pipeline Output
```yaml
Post 1:
  Source: "Attention Head Interpretability" (arXiv:2405.12345)
  Angle: "Practical implications for AI control"
  Visual: Figure 3 from paper (attention heatmap)
  Mentions: ["@JohnDoe (paper author)", "@JaneSmith (domain expert)"]
  Quality Score: 8.7/10
  
Post 2:  
  Source: X.com discussion on AI governance
  Angle: "Community insights on technical standards"
  Visual: Generated quote card
  Mentions: ["@PolicyExpert", "@TechLead"]
  Quality Score: 7.9/10
```

## ⚠️ Content Guidelines
- Always attribute sources
- Respect figure copyrights
- Avoid controversial statements
- Focus on educational value
- Maintain professional tone
